# Generated by Django 5.1 on 2024-08-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='status_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.statusrent'),
        ),
    ]
